### ISSUE TITLE
Files are not stored forever!

### ISSUE THREAD

**Issue by markg85** [coolcode/dfile#3]
Hi,

First of all, thank you for your great application!
It's awesome to see IPFS based solutions in an area where IPFS is really good (hosting files).
And going with support from the command line is just lots of bonus points too!

But...
There are a couple of issues.

First of all, uploads don't work. That's quite a big issue :)
With a file of ~6MB i get this error:
```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

And with a file of just ~300KB i get this error:
```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

Both were with using the dfile ZSH function.
But uploading via the site itself also didn't work for me.

Second, and this i do take issue with as it's highly misleading. You claim files are stored forever. That is quite simply just not true. As you probably know, IPFS relies on pinning to keep files alive. When i'm uploading a file using your service it's likely being pinned on your IPFS instance (it is automatically if you internally do ipfs add ...). And your server, despite your best intentions, will by no means have the ability to hold the promise of keeping all the files online.  I would like to ask you to please clarify this on your site. You could even extend your service a little to add notification support and send the uploader of a file a mail - say - one week before you unpin it. If it doesn't have any pins after that and no recent visits then the file will in fact be gone from IPFS.

Cheers,
Mark

**Comment by coolcode** [comment]
Thanks Mark for your good feedback and suggestions! I’ll check them.

**Comment by coolcode** [comment]
Hi, Mark. The issues are fixed now.  You can try it again. Thanks.
- file limitation: I set the limitation up to 100M. 
- the file is pinned by default

**Comment by coolcode** [comment]
I close issue as there is no more update info.
